name: workflow.yml
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_KEY }}
          port: 22
          script: |
            cd ~/SE-MoaBom-back
            git pull origin main --rebase
            ./gradlew clean build -x test
            pgrep -f "java -jar.*demo-0.0.1-SNAPSHOT.[j]ar" | xargs -r kill -9 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > app.log 2>&1 < /dev/null &